// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WorkoutSection from "../workout-section/WorkoutSection.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

import './workouts.css';
;

function Workouts(props) {
  return JsxRuntime.jsx("div", {
              children: props.workouts.map(function (workout) {
                    return JsxRuntime.jsx(WorkoutSection.make, {
                                workout: workout
                              }, workout.name);
                  }),
              className: "workouts-grid"
            });
}

var make = Workouts;

export {
  make ,
}
/*  Not a pure module */
