// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

import './TestComponent.css'
;

function TestComponent(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                "Hello from ReScript!",
                JsxRuntime.jsx("p", {
                      children: "Banana phone"
                    })
              ],
              className: "test-component"
            });
}

var make = TestComponent;

export {
  make ,
}
/*  Not a pure module */
