// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

import './weekly-plan.css';
;

function WeeklyPlanGrid$DayCard(props) {
  var workout = props.workout;
  var day = props.day;
  var dayName;
  switch (day) {
    case "Monday" :
        dayName = "Monday";
        break;
    case "Tuesday" :
        dayName = "Tuesday";
        break;
    case "Wednesday" :
        dayName = "Wednesday";
        break;
    case "Thursday" :
        dayName = "Thursday";
        break;
    case "Friday" :
        dayName = "Friday";
        break;
    case "Saturday" :
        dayName = "Saturday";
        break;
    case "Sunday" :
        dayName = "Sunday";
        break;
    
  }
  var dayPath;
  switch (day) {
    case "Monday" :
        dayPath = "monday";
        break;
    case "Tuesday" :
        dayPath = "tuesday";
        break;
    case "Wednesday" :
        dayPath = "wednesday";
        break;
    case "Thursday" :
        dayPath = "thursday";
        break;
    case "Friday" :
        dayPath = "friday";
        break;
    case "Saturday" :
        dayPath = "saturday";
        break;
    case "Sunday" :
        dayPath = "sunday";
        break;
    
  }
  var workoutName = workout !== undefined ? workout : "Rest Day";
  var href = "#/weekly-plan/" + dayPath;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("a", {
                      className: "day-card-link",
                      href: href
                    }),
                JsxRuntime.jsx("h2", {
                      children: dayName
                    }),
                JsxRuntime.jsx("p", {
                      children: workoutName
                    })
              ],
              className: "day-card" + (
                workout === undefined ? " rest" : ""
              )
            });
}

var DayCard = {
  make: WeeklyPlanGrid$DayCard
};

function WeeklyPlanGrid(props) {
  var weeklyPlan = props.weeklyPlan;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(WeeklyPlanGrid$DayCard, {
                      day: "Monday",
                      workout: weeklyPlan.monday
                    }),
                JsxRuntime.jsx(WeeklyPlanGrid$DayCard, {
                      day: "Tuesday",
                      workout: weeklyPlan.tuesday
                    }),
                JsxRuntime.jsx(WeeklyPlanGrid$DayCard, {
                      day: "Wednesday",
                      workout: weeklyPlan.wednesday
                    }),
                JsxRuntime.jsx(WeeklyPlanGrid$DayCard, {
                      day: "Thursday",
                      workout: weeklyPlan.thursday
                    }),
                JsxRuntime.jsx(WeeklyPlanGrid$DayCard, {
                      day: "Friday",
                      workout: weeklyPlan.friday
                    }),
                JsxRuntime.jsx(WeeklyPlanGrid$DayCard, {
                      day: "Saturday",
                      workout: weeklyPlan.saturday
                    }),
                JsxRuntime.jsx(WeeklyPlanGrid$DayCard, {
                      day: "Sunday",
                      workout: weeklyPlan.sunday
                    })
              ],
              className: "weekly-plan"
            });
}

var make = WeeklyPlanGrid;

export {
  DayCard ,
  make ,
}
/*  Not a pure module */
