// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TestComponent from "./components/TestComponent.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(TestComponent.make, {}),
              className: "app"
            });
}

var make = App;

export {
  make ,
}
/* TestComponent Not a pure module */
